### ISSUE TITLE
关于“使用软件“的开发思路建议

### ISSUE THREAD

**Issue by PLFJY** [TC999/AppDataCleaner#9]
我看到了“使用软件”的敬请期待
建议如下：可以在仓库内放一个txt，用于放置文件夹对应的软件，然后由大家来提交PR完善这份列表

**Comment by PLFJY** [comment]
同时，一部分系统级别的文件夹建议手动标注并用颜色标识

**Comment by TC999** [comment]
感谢提议。后续测试

**Comment by TC999** [comment]
刚更新，[测试版](https://github.com/TC999/AppDataCleaner/releases/tag/v1.0.3-b3)，谨慎使用
